apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    company: globant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        company: globant
    spec:
      containers:
      - name: front-end
        image: nginx:alpine
        ports:
        - containerPort: 80
