apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init
spec:
  initContainers:
  - name: init-busybox
    image: busybox:1.32.0-uclibc
    command: ["sleep", "5000"]
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
